---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
